INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (1, 'VAN A', 'NGUYEN', 'nguyenvana@gmail.com');
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (2, 'VAN B', 'NGUYEN', 'nguyenvana@gmail.com');
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (3, 'VAN C', 'NGUYEN', 'nguyenvana@gmail.com');
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (4, 'VAN D', 'NGUYEN', 'nguyenvana@gmail.com');
INSERT INTO MOVIES (ID, TITLE, YEAR) VALUES (1, 'Under the Skin', 2013);
INSERT INTO MOVIES (ID, TITLE, YEAR) VALUES (2, 'Holy Motors', 2012);
INSERT INTO MOVIES (ID, TITLE, YEAR) VALUES (3, 'Moonlight', 2016);
INSERT INTO MOVIES (ID, TITLE, YEAR) VALUES (4, 'Little Women', 2019);